### ISSUE TITLE
table expected, got user data

### ISSUE THREAD

**Issue by JoseConseco** [rcarriga/cmp-dap#2]
I'm on latest daily nvim build. And latest cmp. O get this error in dap-repl:
![image](https://user-images.githubusercontent.com/13521338/168484478-ba95b52d-51ab-44a5-b8c6-073b9b9810cb.png)
Any ideas how to fix it?

**Comment by JoseConseco** [comment]
My bad I thought I saw  cmp-dap in the error. Closing.

**Comment by JoseConseco** [comment]
After all I think this may by caused by

```lua
enabled = function ()
    return vim.api.nvim_buf_get_option(0, "buftype") ~= "prompt"
      or require("cmp_dap").is_dap_buffer()
  end,
```
Which enabled cmp in repl, which gives now error. Is there any way to disable all sources, except cmp-dap for  dap-repl?

**Comment by rcarriga** [comment]
Same as described in #1. This is not an error by cmp-dap but cmp-buffer. As far as I'm aware a user can't disable certain sources per buffer. Happy to be corrected though :smile: 

I'd suggest opening a bug report there so that prompt buffers can be handled properly or the source can be disabled for them

**Comment by JoseConseco** [comment]
Ok.  I think I saw people requesting similar feature for cmp-dap  (ability to limit certain sources per filetype).  Closing this then.

**Comment by Abh15h3k** [comment]
you could setup cmp-dap just for dap-repl using filetype

```
require("cmp").setup.filetype("dap-repl", {
    sources = {
        { name = "dap" }
    }
})
```

**Comment by JoseConseco** [comment]
Thanks. It seem it works!
