### ISSUE TITLE
Why were these setup instructions removed from the readme?

### ISSUE THREAD

**Issue by zzzachzzz** [rcarriga/cmp-dap#3]
In this commit, some suggested configuration from the readme was removed:
https://github.com/rcarriga/cmp-dap/commit/e21f0e5d188ee428f8acab1af21839af391607a4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L8-L13

>-- nvim-cmp by defaults disables autocomplete for prompt buffers

Completions weren't working for me until I added that configuration.

**Comment by Danielhp95** [comment]
Same for me

**Comment by rcarriga** [comment]
Because it caused issues for other sources (see #1 #2). Interestingly it did work before without it but now it seems to require both. I've updated the README to include both instructions
