### ISSUE TITLE
How to make it work

### ISSUE THREAD

**Issue by nieomylnieja** [rcarriga/cmp-dap#5]
Silly question, but I can't seem to use it with Neovim 0.8.0.
My `cmp` config is quiet vast so I removed everything and just left the stuff from the README.
It still doesn't work and `CmpStatus` lists `cmp-dap` under unavailable source names.
Any rough ideas/caveats with this one?

**Comment by rcarriga** [comment]
The setup in the README means it'll only work for nvim-dap/nvim-dap-ui buffers, not all buffers. Are you trying it in the nvim-dap REPL? If so, can you paste your config?

**Comment by nieomylnieja** [comment]
ye, I am trying it out for the right buffers, I'm using `dap-ui`, but double tested it with `echo &ft` to be sure I'm in the supported ones. My main concern here is the fact that `CmpStatus` has it under unavailable sources:

```markdown
# unavailable source names
- cmp-dap

# unused source names
- buffer
- cmdline
- nvim_lsp_signature_help
- path
- luasnip
```

Here's my config (at least the `cmp` part), I literally commented out all the stuff I had in there and pasted in the README suggestions:

```lua
require("cmp").setup({
  enabled = function()
    return vim.api.nvim_buf_get_option(0, "buftype") ~= "prompt"
        or require("cmp_dap").is_dap_buffer()
  end
})

require("cmp").setup.filetype({ "dap-repl", "dapui_watches", "dapui_hover" }, {
  sources = {
    { name = "dap" },
  },
})
```

**Comment by rcarriga** [comment]
Ah sorry I forgot to ask, what adapter are you using? Not all of them will support completion requests unfortunately. If you enable the nvim-dap debug logs, it will show the server capabilities which should have `supportsCompletionsRequest = true`

**Comment by nieomylnieja** [comment]
You're right, I assumed it's universal and does not depend on the concrete DAP implementation, I ran it initially with Go's `delve` but now verified it with debugpy and lldb and it works just fine ;)
It might be worth adding that to the README as a disclaimer (I can create the PR If you wish me to), I don't think many people have a deep enough understanding of DAP to not get confused by it. Thanks for the answer!

**Comment by rcarriga** [comment]
Ah good point, I've added a note to the README with an easy way for users to check :smile:

**Comment by nieomylnieja** [comment]
Cool, thanks for updating the `README` :)
